# Generated by Django 4.2.8 on 2024-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_profile_nickname_position_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary_coef',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
