# Generated by Django 5.1 on 2024-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_department_alter_profile_gender_profile_department'),
    ]

