# Generated by Django 5.1 on 2024-10-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_profile_department'),
    ]

