# Generated by Django 5.1.3 on 2024-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_alter_sheet_ot"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
