# Generated by Django 4.2.8 on 2024-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_profile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('working', 'Đang làm'), ('on_leave', 'Nghỉ phép'), ('resigned', 'Đã nghỉ việc')], default='working', max_length=20),
        ),
    ]
