# Generated by Django 4.2.8 on 2024-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_address_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='work_hour',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
