# Generated by Django 5.1 on 2024-10-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_department_salary_profile_degree_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('Đại học', 'Đại học'), ('Cao đẳng', 'Cao đẳng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.position'),
        ),
    ]
