# Generated by Django 5.1.3 on 2024-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_rename_ten_topicletter_name_alter_letter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="ot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("Đúng Giờ", "Đúng Giờ"),
                    ("Đến Muộn", "Đến Muộn"),
                ],
                default="Đúng Giờ",
                max_length=20,
            ),
        ),
    ]
