# Generated by Django 5.1.3 on 2024-11-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_sheet_ot_alter_sheet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="ot",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
