# Generated by Django 5.1.3 on 2024-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_dayoffrequest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="late_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
