# Generated by Django 5.1 on 2024-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_profile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
